sudo: required

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends texlive texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-beamer latex-xcolor
- sudo tlmgr install droid graphicx minted pgfpages fvextra upquote

script:
- mkdir build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory build Example_Presentation.tex

# deploy:
#   provider: releases
#   api_key:
#     secure: [YOUR KEY]
#   file:
#   - build/Example_Presentation.pdf
#   skip_cleanup: true
#   on:
#     tags: true
