sudo: required

before_install:
  - sudo apt-get install makejvf
  - cd .buildscripts
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x install-tl-ubuntu && sudo ./install-tl-ubuntu --profile $TRAVIS_BUILD_DIR/.buildscripts/texlive.profile
  - sudo /usr/local/texlive/bin/x86_64-linu/tlmgr install droid graphicx minted pgfpages fvextra upquote

script:
  - mkdir build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory build Example_Presentation.tex

# deploy:
#   provider: releases
#   api_key:
#     secure: [YOUR KEY]
#   file:
#   - build/Example_Presentation.pdf
#   skip_cleanup: true
#   on:
#     tags: true
