sudo: required

env:
  - LATEX_PARA="-shell-escape -interaction=nonstopmode -halt-on-error -output-directory build"

before_install:
  - sudo pip install Pygments
  - cd .buildscripts
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x install-tl-ubuntu && sudo ./install-tl-ubuntu --profile ${TRAVIS_BUILD_DIR}/.buildscripts/texlive.profile
  - sudo /opt/texbin/tlmgr install chktex beamer xcolor pgf droid minted fvextra upquote slantsc ifplatform xstring framed
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - /opt/texbin/chktex Example_Presentation.tex
  - mkdir build

script:
  - /opt/texbin/pdflatex ${LATEX_PARA} Example_Presentation.tex > /dev/null
  - /opt/texbin/bibtex build/Example_Presentation.aux > /dev/null
  - /opt/texbin/pdflatex ${LATEX_PARA} Example_Presentation.tex > /dev/null
  - /opt/texbin/pdflatex ${LATEX_PARA} Example_Presentation.tex > /dev/null

after_failure:
  # - ls /opt/texbin
  # - cat $TRAVIS_BUILD_DIR/.buildscripts/install-tl-1.log
  # - ls ${TRAVIS_BUILD_DIR}
  - cat build\Example_Presentation.log

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "build/Example_Presentation.pdf"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
